version: 'latest'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: 'uvicorn src.main:fastapi_app --reload --host 0.0.0.0 --port 8000 --factory'
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./data/postgres/:/var/lib/postgres
    ports:
      - '5432:5432'
    env_file:
      .env

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./data/dbdata6/:/var/lib/mongodb
    env_file:
      .env
