"""Change fields

Revision ID: 6b57c8b1b478
Revises: 32d3c0365a00
Create Date: 2024-05-19 17:26:28.078323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b57c8b1b478'
down_revision: Union[str, None] = '32d3c0365a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('reviews', 'text')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'username')
    op.add_column('reviews', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'content')
    # ### end Alembic commands ###
